package modal;
/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int PROGRAM = 10;
  /** RegularExpression Id. */
  int EXECUTE = 11;
  /** RegularExpression Id. */
  int THIS = 12;
  /** RegularExpression Id. */
  int PURPOSE = 13;
  /** RegularExpression Id. */
  int DECLARE = 14;
  /** RegularExpression Id. */
  int AS = 15;
  /** RegularExpression Id. */
  int CONSTANT = 16;
  /** RegularExpression Id. */
  int VARIABLE = 17;
  /** RegularExpression Id. */
  int INTEGER = 18;
  /** RegularExpression Id. */
  int REAL = 19;
  /** RegularExpression Id. */
  int STRING = 20;
  /** RegularExpression Id. */
  int BOOLEAN = 21;
  /** RegularExpression Id. */
  int ASSIGN = 22;
  /** RegularExpression Id. */
  int ACQUIRE = 23;
  /** RegularExpression Id. */
  int SHOW = 24;
  /** RegularExpression Id. */
  int PUT = 25;
  /** RegularExpression Id. */
  int CHECK = 26;
  /** RegularExpression Id. */
  int TRUE = 27;
  /** RegularExpression Id. */
  int RESULT = 28;
  /** RegularExpression Id. */
  int UNTRUE = 29;
  /** RegularExpression Id. */
  int CARRY = 30;
  /** RegularExpression Id. */
  int OUT = 31;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 32;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 33;
  /** RegularExpression Id. */
  int DOT = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int PLUS = 36;
  /** RegularExpression Id. */
  int MINUS = 37;
  /** RegularExpression Id. */
  int MULTIPLY = 38;
  /** RegularExpression Id. */
  int DIVIDER = 39;
  /** RegularExpression Id. */
  int POW = 40;
  /** RegularExpression Id. */
  int PERCENT = 41;
  /** RegularExpression Id. */
  int MOD = 42;
  /** RegularExpression Id. */
  int EQUALS = 43;
  /** RegularExpression Id. */
  int DIFFERENT = 44;
  /** RegularExpression Id. */
  int LESS = 45;
  /** RegularExpression Id. */
  int GREATER = 46;
  /** RegularExpression Id. */
  int LESS_EQUAL = 47;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 48;
  /** RegularExpression Id. */
  int AMPERSAND = 49;
  /** RegularExpression Id. */
  int PIPE = 50;
  /** RegularExpression Id. */
  int EXCLAMATION = 51;
  /** RegularExpression Id. */
  int DIGIT = 52;
  /** RegularExpression Id. */
  int DECIMAL_NUMBER = 53;
  /** RegularExpression Id. */
  int NUMBER_INTEGER = 54;
  /** RegularExpression Id. */
  int NUMBER_REAL = 55;
  /** RegularExpression Id. */
  int STRLIT = 57;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int commentmultiline = 1;
  /** Lexical state. */
  int WithinString = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"kk-\"",
    "\"-kk\"",
    "<token of kind 9>",
    "<PROGRAM>",
    "<EXECUTE>",
    "<THIS>",
    "<PURPOSE>",
    "<DECLARE>",
    "<AS>",
    "<CONSTANT>",
    "<VARIABLE>",
    "<INTEGER>",
    "<REAL>",
    "<STRING>",
    "<BOOLEAN>",
    "<ASSIGN>",
    "<ACQUIRE>",
    "<SHOW>",
    "<PUT>",
    "<CHECK>",
    "<TRUE>",
    "<RESULT>",
    "<UNTRUE>",
    "<CARRY>",
    "<OUT>",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"%\"",
    "\"%%\"",
    "\"==\"",
    "\"!=\"",
    "\"<<\"",
    "\">>\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "<DIGIT>",
    "<DECIMAL_NUMBER>",
    "<NUMBER_INTEGER>",
    "<NUMBER_REAL>",
    "\"\\\"\"",
    "\"\\\"\"",
    "<token of kind 58>",
  };

}
