/**
 * Classe KcompilerView
 * 
 * @author Gabriel Hegler Klok
 * @since 2019/08
 */
package view;

public class KcompilerView extends javax.swing.JFrame {

    /**
     * Creates new form KcompilerView
     */
    public KcompilerView() {
        initComponents();
        TextLineNumber contLine = new TextLineNumber(inputArea);
        scrollInput.setRowHeaderView(contLine);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollInput = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextArea();
        scrollOutput = new javax.swing.JScrollPane();
        helpline = new javax.swing.JLabel();
        btnNewDocument = new javax.swing.JButton();
        btnOpenDocument = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCopy = new javax.swing.JButton();
        btnPaste = new javax.swing.JButton();
        btnCut = new javax.swing.JButton();
        btnCompile = new javax.swing.JButton();
        btnExecute = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemNew = new javax.swing.JMenuItem();
        menuItemOpen = new javax.swing.JMenuItem();
        menuItemSave = new javax.swing.JMenuItem();
        menuItemSaveAs = new javax.swing.JMenuItem();
        separatorMenuFile = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        menuEdition = new javax.swing.JMenu();
        menuItemCopy = new javax.swing.JMenuItem();
        menuItemPaste = new javax.swing.JMenuItem();
        menuItemCut = new javax.swing.JMenuItem();
        menuCompilation = new javax.swing.JMenu();
        menuItemCompile = new javax.swing.JMenuItem();
        menuItemExecute = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kcompiler");
        setMinimumSize(new java.awt.Dimension(800, 660));
        setPreferredSize(new java.awt.Dimension(800, 660));

        scrollInput.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollInput.setAutoscrolls(true);

        inputArea.setColumns(20);
        inputArea.setRows(5);
        inputArea.setBorder(null);
        scrollInput.setViewportView(inputArea);

        scrollOutput.setToolTipText("");
        scrollOutput.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollOutput.setAutoscrolls(true);

        helpline.setText("linha 1, coluna 1");
        helpline.setAutoscrolls(true);

        btnNewDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/document-new.png"))); // NOI18N
        btnNewDocument.setToolTipText("New document");
        btnNewDocument.setName(""); // NOI18N
        btnNewDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDocumentActionPerformed(evt);
            }
        });

        btnOpenDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/document-open.png"))); // NOI18N
        btnOpenDocument.setToolTipText("Open document");

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/save.png"))); // NOI18N
        btnSave.setToolTipText("Save");

        btnCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/copy.png"))); // NOI18N
        btnCopy.setToolTipText("Copy");

        btnPaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/paste.png"))); // NOI18N
        btnPaste.setToolTipText("Paste");

        btnCut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/cut.png"))); // NOI18N
        btnCut.setToolTipText("Cut");

        btnCompile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/compiler.png"))); // NOI18N
        btnCompile.setToolTipText("Compile");

        btnExecute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/execute.png"))); // NOI18N
        btnExecute.setToolTipText("Execute");

        menuFile.setText("File");

        menuItemNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/document-new.png"))); // NOI18N
        menuItemNew.setText("New");
        menuFile.add(menuItemNew);

        menuItemOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/document-open.png"))); // NOI18N
        menuItemOpen.setText("Open");
        menuFile.add(menuItemOpen);

        menuItemSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/save.png"))); // NOI18N
        menuItemSave.setText("Save");
        menuFile.add(menuItemSave);

        menuItemSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/save-as.png"))); // NOI18N
        menuItemSaveAs.setText("Save As");
        menuFile.add(menuItemSaveAs);

        separatorMenuFile.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        menuFile.add(separatorMenuFile);

        menuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/exit.png"))); // NOI18N
        menuItemExit.setText("Exit");
        menuFile.add(menuItemExit);

        menuBar.add(menuFile);

        menuEdition.setText("Edition");

        menuItemCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/copy.png"))); // NOI18N
        menuItemCopy.setText("Copy");
        menuEdition.add(menuItemCopy);

        menuItemPaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/paste.png"))); // NOI18N
        menuItemPaste.setText("Paste");
        menuEdition.add(menuItemPaste);

        menuItemCut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/cut.png"))); // NOI18N
        menuItemCut.setText("Cut");
        menuEdition.add(menuItemCut);

        menuBar.add(menuEdition);

        menuCompilation.setText("Compilation");

        menuItemCompile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/compiler.png"))); // NOI18N
        menuItemCompile.setText("Compile");
        menuCompilation.add(menuItemCompile);

        menuItemExecute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/execute.png"))); // NOI18N
        menuItemExecute.setText("Execute");
        menuCompilation.add(menuItemExecute);

        menuBar.add(menuCompilation);

        menuAbout.setText("About");
        menuBar.add(menuAbout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helpline, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewDocument)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenDocument)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCopy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPaste)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCompile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExecute)))
                .addGap(0, 500, Short.MAX_VALUE))
            .addComponent(scrollInput, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(scrollOutput, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnNewDocument, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOpenDocument, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCopy)
                            .addComponent(btnPaste)
                            .addComponent(btnCut)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCompile)
                        .addComponent(btnExecute)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollInput, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(scrollOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDocumentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewDocumentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void startScreen(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KcompilerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KcompilerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KcompilerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KcompilerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KcompilerView().setVisible(true);   
            }
        }); 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompile;
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnCut;
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton btnNewDocument;
    private javax.swing.JButton btnOpenDocument;
    private javax.swing.JButton btnPaste;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel helpline;
    private javax.swing.JTextArea inputArea;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCompilation;
    private javax.swing.JMenu menuEdition;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemCompile;
    private javax.swing.JMenuItem menuItemCopy;
    private javax.swing.JMenuItem menuItemCut;
    private javax.swing.JMenuItem menuItemExecute;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemNew;
    private javax.swing.JMenuItem menuItemOpen;
    private javax.swing.JMenuItem menuItemPaste;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JMenuItem menuItemSaveAs;
    private javax.swing.JScrollPane scrollInput;
    private javax.swing.JScrollPane scrollOutput;
    private javax.swing.JPopupMenu.Separator separatorMenuFile;
    // End of variables declaration//GEN-END:variables
}
